<?php

namespace AppBundle\Repository;

/**
 * AngelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GodRepository extends \Doctrine\ORM\EntityRepository
{
}
