<?php

namespace AppBundle\Repository;

/**
 * ImplantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImplantRepository extends \Doctrine\ORM\EntityRepository
{
}
