<?php

namespace AppBundle\Repository;

/**
 * ImplantModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImplantModelRepository extends \Doctrine\ORM\EntityRepository
{
}
