<?php

namespace AppBundle\Repository;

/**
 * InventoryItemModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryItemModelRepository extends \Doctrine\ORM\EntityRepository
{
}
