<?php

namespace AppBundle\Repository;

/**
 * InventoryModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryModelRepository extends \Doctrine\ORM\EntityRepository
{
}
