<?php

namespace AppBundle\Repository;

/**
 * ItemModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemModelRepository extends \Doctrine\ORM\EntityRepository
{
}
