<?php

namespace AppBundle\Repository;

/**
 * PersonageModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonageModelRepository extends \Doctrine\ORM\EntityRepository
{
}
