<?php

namespace AppBundle\Repository;

/**
 * PostureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostureRepository extends \Doctrine\ORM\EntityRepository
{
}
