<?php

namespace AppBundle\Repository;

/**
 * WeaponModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponModelRepository extends \Doctrine\ORM\EntityRepository
{
}
