<?php

namespace AppBundle\Repository;

/**
 * WoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WoundRepository extends \Doctrine\ORM\EntityRepository
{
}
